export const tutorData = [
  {
    id: "007",
    name: "stella",
    course: "English",
    img: "./tutor-img/one.jpg",
    rating: "3",
  },
  {
    id: "710",
    name: "Rachel",
    course: "Spanish",
    img: "./tutor-img/two.jpg",
    rating: "2",
  },
  {
    id: "350",
    name: "Lilly",
    course: "Science",
    img: "./tutor-img/three.jpg",
    rating: "5",
  },
  {
    id: "310",
    name: "Ahamed",
    course: "Social",
    img: "./tutor-img/four.jpg",
    rating: "3",
  },
  {
    id: "418",
    name: "Daniel",
    course: "Grammer",
    img: "./tutor-img/five.jpg",
    rating: "3",
  },
  {
    id: "420",
    name: "Malini",
    course: "English",
    img: "./tutor-img/one.jpg",
    rating: "3",
  },
  {
    id: "117",
    name: "Angel",
    course: "Maths",
    img: "./tutor-img/two.jpg",
    rating: "1",
  },
  {
    id: "217",
    name: "Merlin",
    course: "English",
    img: "./tutor-img/three.jpg",
    rating: "3",
  },
];
